# Exception
![Exception-Class](https://github.com/chucoding/today-i-learned/assets/56211193/ae72c868-e27c-4469-a9a3-b7ae3cb67684)

|클래스명|설명|
|---|---|
|Error|심각한 수준의 오류, 프로그램이 중단됨(ex. OutOfMemoryError)|
|Exception|프로그램의 예외적인 상황(try catch 또는 throw등을 이용하여 논리적으로 처리가능)|
|Checked Exception|반드시 예외처리구문(try catch)을 사용해야함(처리 안하면 컴파일 에러 발생)(ex. IOException, SQLException, ConnectException)|
|Unchecked Exception|RuntimeException 하위 클래스(ex. NullPointException, IndexOutOfBoundsException)|

# Custom Exception
사용자 정의 예외처리 (상속받아서 만든다. 내용은 굳이 없어도 되지만 보통 아래처럼 생성자로 구성함)

```
class CustomException extends Exception {

    // 생성자를 이용한 예외 만들기
    public CustomException(String message) {
        super(message);
    }

    public CustomException(String message, Throwable cause) {
		super(message, cause);
	}

    // 오버라이드를 통한 에러메시지 만들기
    @Override
    public String getMessage() {
        return "error";
    }
}
```

💡 만약 Exeption 대신 RuntimeException을 상속받는다면 별도로 throws를 사용하지 않아도 저절로 throw 된다.(?)

💡 throws가 적용된 메소드를 호출하려면 try-catch구문을 이용한 예외처리가 필요하다 -> checked(?)

Q. 다음과 같은 상황일 때 출력되는 값 알아맞춰보기
```
try {
    throw new NullPointException();
} catch (NullPointerException e1) { //동작상 필요
    System.out.println("널포인터 참조 예외");
} catch (Exception e2) { //문법상 필요 - 없으면 에러
    System.out.println("모든 예외");
}finally {
    System.out.println("무조건 실행");
}
        
System.out.println("+ + + 프로그램 정상 종료 + + +");
```

# RestClientException
RestTemplate에서 사용하고 있는 Exception<br>
<i>※ 요즘은 RestTemplate 대신 WebClient를 많이 쓴다. 추후에 리팩토링 필요</i>

![다운로드](https://github.com/chucoding/today-i-learned/assets/56211193/e9089b7a-3ab0-4566-8bb3-e2130443f923)
RuntimeException을 상속하기 때문에 try-catch 또는 throws를 추가하지 않아도 됨.

|클래스명|설명|
|---|---|
|ResourceAccessException|외부 리소스와의 통신에서 예외가 발생할 때 던져지는 예외(네트워크 문제, 타임아웃, 연결이 끊겼을 때 등)|
|RestClientResponseException|실제 HTTP 응답 데이터를 포함하고 있는 예외클래스들의 공통 기반 클래스|
